// renderer/modules/webbridge/adapters.js —— 出站桥站点适配器注册表（纯数据，可热更）
// mode：markdown=MD直贴 / paste-html=HTML粘贴注入(P1) / manual=剪贴板兜底
export const ADAPTERS = [
  {
    id: 'juejin', name: '掘金',
    url: 'https://juejin.cn/editor/drafts/new',
    home: 'https://juejin.cn',
    mode: 'markdown',
    title: 'input[placeholder*="标题"], .title-input input, input.title-input',
    editors: ['.CodeMirror', 'textarea'],
    ready: '.CodeMirror, textarea',
    login: '.avatar, .main-avatar, [class*=avatar]',
    note: 'Markdown 直贴；本地图片需手动上传（编辑器粘贴图片会自动传）',
  },
  {
    id: 'csdn', name: 'CSDN',
    url: 'https://editor.csdn.net/md/',
    home: 'https://www.csdn.net',
    mode: 'markdown',
    title: '.editor__title, input[placeholder*="标题"]',
    editors: ['.CodeMirror', 'textarea'],
    ready: '.CodeMirror, textarea, .editor__title',
    login: '.avatar, [class*=avatar], .user-photo',
    note: 'Markdown 直贴（编辑器默认 MD 模式）',
  },
  {
    id: 'jianshu', name: '简书',
    url: 'https://www.jianshu.com/writer',
    home: 'https://www.jianshu.com',
    mode: 'markdown',
    title: 'input[placeholder*="标题"], ._24C7u',
    editors: ['textarea', '.CodeMirror'],
    ready: 'textarea, .CodeMirror, ._24C7u',
    login: '.avatar, [class*=avatar]',
    note: '简书需在设置中切到 Markdown 编辑器；否则走剪贴板兜底',
  },
  {
    id: 'zhihu', name: '知乎',
    url: 'https://zhuanlan.zhihu.com/write',
    home: 'https://www.zhihu.com',
    mode: 'paste-html',
    title: '.WriteIndex-titleInput, textarea[placeholder*="标题"]',
    editors: ['.public-DraftEditor-content', '[contenteditable]'],
    ready: '.public-DraftEditor-content, [contenteditable]',
    login: '.Avatar, .AppHeader-profileAvatar, [class*=Avatar]',
    note: 'HTML 粘贴注入；本地图片自动随粘贴上传',
  },
  {
    id: 'bilibili', name: 'B站专栏',
    url: 'https://member.bilibili.com/platform/upload/text',
    home: 'https://www.bilibili.com',
    mode: 'paste-html',
    title: 'input[placeholder*="标题"], .title-input',
    editors: ['.ql-editor', '[contenteditable]', '.editor'],
    ready: '.ql-editor, [contenteditable], .editor',
    login: '.header-avatar, [class*=avatar]',
    note: 'HTML 粘贴注入；本地图片自动随粘贴上传',
  },
  {
    id: 'manual', name: '其他站点（手动粘贴）',
    url: '', home: '', mode: 'manual',
    note: '复制 Markdown 源文到剪贴板并打开你给的页面，Ctrl+V 即可',
  },
];
